# https://docs.mattermost.com/scale/deploy-prometheus-grafana-for-performance-monitoring.html
---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:

rule_files:

scrape_configs:
  - job_name: mattermost
    static_configs:
      - targets: ["mattermost:1234"]
